In [ ]:
pip install numpy

In [4]:
#1D array
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
#2D array
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [11]:
#rangenp.arange(0,10,2)

In [10]:
#random
np.random.rand(3)

array([0.45314934, 0.60064148, 0.66861111])

In [12]:
a=np.array([1,4,9])
print(np.sqrt(a))
print(np.mean(a))

[1. 2. 3.]
4.666666666666667
